-- MySQL Script generated by MySQL Workbench
-- Wed Mar  2 09:51:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` DEFAULT CHARACTER SET utf8 ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NOT NULL,
  `firstname` VARCHAR(150) NOT NULL,
  `lastname` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `age` SMALLINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`user_role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_fk` INT UNSIGNED NOT NULL,
  `role_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_fk_user_idx` (`user_fk` ASC),
  INDEX `role_fk_user_role_idx` (`role_fk` ASC),
  CONSTRAINT `user_fk_user`
    FOREIGN KEY (`user_fk`)
    REFERENCES `database`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_fk_user_role`
    FOREIGN KEY (`role_fk`)
    REFERENCES `database`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`article` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NULL,
  `date_add` DATETIME NOT NULL,
  `date_uptade` DATETIME NOT NULL,
  `user_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `article_fk_user_idx` (`user_fk` ASC),
  CONSTRAINT `article_fk_user`
    FOREIGN KEY (`user_fk`)
    REFERENCES `database`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `user_fk` INT UNSIGNED NOT NULL,
  `article_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_fk_user_idx` (`user_fk` ASC),
  INDEX `comments_fk_article_idx` (`article_fk` ASC),
  CONSTRAINT `user_fk_user_comments`
    FOREIGN KEY (`user_fk`)
    REFERENCES `database`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comments_fk_article`
    FOREIGN KEY (`article_fk`)
    REFERENCES `database`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
